CREATE TABLE PLAYER_INFO
(
   PID          VARCHAR2 (40),
   PASS         VARCHAR2 (40),
   PNAME        VARCHAR2 (40),
   EMAIL        VARCHAR2 (40),
   TEL          VARCHAR2 (40),
   MCHOICE      NUMBER,
   TOTBET       NUMBER,
   TOTBENEFIT   NUMBER,
   TOTLOSE      NUMBER,
   CURMONEY     NUMBER,
   FIRST        NUMBER,
   SECOND       NUMBER,
   THIRD        NUMBER
);
commit;

CREATE TABLE HORSE_INFO
(
	HNAME VARCHAR2(100),
	HNUM NUMBER,
	BIRTHDATE DATE,
	GENDER VARCHAR2(4),
	COLOR VARCHAR2(20),
	REGDATE DATE,
	COUNTRY VARCHAR2(100),
	FATHER VARCHAR2(100),
	MOTHER VARCHAR2(100),
	TRANERNAME VARCHAR2(100),
	OWNERNAME VARCHAR2(100)
	);
	
	DROP TABLE HORSE_INFO;

insert into HORSE_INFO VALUES('가락공원', 029981, 2011-04-07,'수', '흑갈색', 2013-12-08, '한국', '볼포니', '금강공원', '조용배(12)', '오영희');
	

